### ISSUE TITLE
getting null pointer exception when trying to use this plugin

### ISSUE THREAD

**Issue by roneny1** [maximecharron/statistics-notification-plugin#4]
Hi

I followed your instructions and when I start a job I get the following exception in Jenkins log
any idea what could cause it ? my jenkins version is 2.9

Thanks
Ronen

Feb 26, 2017 5:33:27 PM org.jenkins.plugins.statistics.gatherer.listeners.RunStatsListener onStarted WARNING: Failed to call API http://product.com/api/jenkins/all/ for build #562 java.lang.NullPointerException at org.jenkins.plugins.statistics.gatherer.listeners.RunStatsListener.onStarted(RunStatsListener.java:51) at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240) at hudson.maven.MavenBuild$ProxyImpl2.start(MavenBuild.java:572) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at hudson.model.Executor$2.call(Executor.java:934) at hudson.util.InterceptingProxy$1.invoke(InterceptingProxy.java:23) at com.sun.proxy.$Proxy96.start(Unknown Source) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:884) at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:859) at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:818) at hudson.remoting.UserRequest.perform(UserRequest.java:153) at hudson.remoting.UserRequest.perform(UserRequest.java:50) at hudson.remoting.Request$2.run(Request.java:332) at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68) at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18) at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21) at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by maximecharron** [comment]
Hi Ronen,

Which version of the plugin are you using?

**Comment by roneny1** [comment]
Hi Maxim

we are using latest and greatest :-) it seams that in order to make it sent the date we needed to change the property loader in postToService function 
it always returned false to us and we didn't understood why ?
(PropertyLoader.getShouldSendApiHttpRequests()    -   return false)

of course all the configuration on jenkins side was set as defined in the guideline.

Thanks
Ronen

**Comment by maximecharron** [comment]
I'll take a look sometimes this week. It should be around Thurday since the beginning of my week is pretty busy.

**Comment by roneny1** [comment]
now worries, since currently we got a work around

**Comment by maximecharron** [comment]
Hey @roneny1 sorry for the long time to answer. It has been fixed in the latest release.

**Comment by roneny1** [comment]
Thanks ! I will take a look and update.
